// Purpose: Addon management
// Created on: 5/1/26 @ 2:29 AM

const {existsSync} = require("fs")
const {execSync} = require("child_process")

const Strings = require("../strings")
const Paths = require("../paths")
const Logger = require("../logger")
const fetchit = require("../fetchit")
const Game = require("../game")
const Configuration = require("../configuration")
const FilesystemWrapper = require("../filesystem_wrapper")

let mods = null
let dependencies = null

module.exports.initialize = async () => {
    // FIXME: This sucks, but there isn't really much we can do about it... Too bad.
    mods = await (await fetchit(Configuration.getDataURL())).json()
    dependencies = []

    for (const addon of mods.response.publishedfiledetails) {
        if (addon.result === 1)
            continue

        addon.title = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
        addon.description = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
        addon.tags = [{tag: "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"}]
    }

    try {
        dependencies = await (await fetchit(Configuration.getAddonsDependenciesURL())).json()
    } catch {
        // intentionally ignored
    }
}

module.exports.getAll = () => mods.response.publishedfiledetails

module.exports.get = (addonName, fuzzy) => {
    addonName = addonName.toLowerCase()

    let checkTitle = title => title.toLowerCase().includes(addonName)
    let checkDescription = description => checkTitle(description)

    if (!fuzzy) {
        checkTitle = title => title.toLowerCase() === addonName
        checkDescription = _ => false
    }

    return mods.response.publishedfiledetails.filter(addon => addon.publishedfileid === addonName || checkTitle(addon.title) || checkDescription(addon.description) || (fuzzy && addon.tags.filter(tag => tag.tag.toLowerCase().includes(addonName)).length !== 0))
}

const internalInstall = async (path, addon) => {
    if (existsSync(`${path}/${addon.publishedfileid}.${Game.getAddonExtension()}`)) {
        Logger.error(`Already downloaded addon: [${addon.publishedfileid}] ${Strings.removeNewlineEnd(addon.title)}`)
        return
    }

    Logger.log(`Downloading: [${addon.publishedfileid}] ${Strings.removeNewlineEnd(addon.title)}`)

    const vpk = await fetchit(Configuration.getVPKURL(addon.publishedfileid))

    if (!vpk.ok) {
        Logger.error("Error while trying to download addon from server")
        process.exit(5)
    }

    FilesystemWrapper.writeFile(`${path}/${addon.publishedfileid}.${Game.getAddonExtension()}`, await vpk.bytes())

    const jpg = await fetchit(Configuration.getJPGURL(addon.publishedfileid))

    if (!jpg.ok)
        return

    FilesystemWrapper.writeFile(`${path}/${addon.publishedfileid}.jpg`, await jpg.bytes())

    // FIXME: Extracting addons can break certain addons.
    //        Adding the image to the VPK via `--add-image` seems broken right now.
    //        And trying the repack the addon seems to randomly hang.
    if (path !== Paths.getConfiguration())
        return

    // TODO: Not all games uses VPK
    let vpkedit = null

    try {
        vpkedit = execSync("command -v vpkeditcli").toString()
        vpkedit = vpkedit.substring(0, vpkedit.length - 1)
    } catch {
        Logger.error("VPKEdit is not installed. Unable to fix addon images")
        return
    }

    let magick = null

    try {
        magick = execSync("command -v magick").toString()
        magick = magick.substring(0, magick.length - 1)
    } catch {
        Logger.error("ImageMagick is not installed. Unable to fix addon images")
        return
    }

    try {
        execSync(`${vpkedit} "${path}/${addon.publishedfileid}.${Game.getAddonExtension()}" -o "${path}" --extract > /dev/null`)
    } catch {
        Logger.error("Failed to extract addon")
        return
    }

    if (!existsSync(`${path}/${addon.publishedfileid}`)) {
        Logger.error("Addon folder doesn't exist? Was the addon downloaded correctly?")
        return
    }

    try {
        execSync(`${magick} "${path}/${addon.publishedfileid}.jpg" -strip -sampling-factor 4:2:0 "${path}/${addon.publishedfileid}/addonimage.jpg"`)
    } catch {
        Logger.error("Failed to fix image")
    }

    if (!existsSync(`${path}/${addon.publishedfileid}/addoninfo.txt`)) {
        // TODO: Some flags are never set
        // TODO: This is very L4D2 specific
        FilesystemWrapper.writeFile(`${path}/${addon.publishedfileid}/addoninfo.txt`,
            `"AddonInfo"
{
// Generated by SourceAddonsManager
\taddonversion\t\t"0.0"
\taddontitle\t\t\t"${Strings.removeNewlineEnd(addon.title.replaceAll("\"", "")).substring(0, 127)}"
\taddonauthor\t\t\t"${addon.creator.substring(0, 119)}"
\taddonDescription\t"${addon.description.substring(0, 1023).replaceAll("\"", "'")}"

\taddonContent_Campaign\t\t${addon.tags.filter(tag => tag.tag === "Campaigns").length !== 0 ? "1" : "0"}
\taddonContent_Map\t\t\t${addon.tags.filter(tag => tag.tag === "Campaigns").length !== 0 ? "1" : "0"}
\taddonContent_Skin\t\t\t${(addon.tags.filter(tag => tag.tag === "Textures").length !== 0 || addon.tags.filter(tag => tag.tag === "Models").length !== 0) ? "1" : "0"}
\taddonContent_weapon\t\t\t${addon.tags.filter(tag => tag.tag === "Weapons").length !== 0 ? "1" : "0"}
\taddonContent_BossInfected\t${(addon.tags.filter(tag => tag.tag === "Witch").length !== 0 || addon.tags.filter(tag => tag.tag === "Tank").length !== 0) ? "1" : "0"}
\taddonContent_CommonInfected\t${addon.tags.filter(tag => tag.tag === "Common Infected").length !== 0 ? "1" : "0"}
\taddonContent_Survivor\t\t${addon.tags.filter(tag => tag.tag === "Survivors").length !== 0 ? "1" : "0"}
\taddonContent_Sound\t\t\t${addon.tags.filter(tag => tag.tag === "Sounds").length !== 0 ? "1" : "0"}
\taddonContent_Music\t\t\t${addon.tags.filter(tag => tag.tag === "Sounds").length !== 0 ? "1" : "0"}
\taddonContent_Script\t\t\t${addon.tags.filter(tag => tag.tag === "Scripts").length !== 0 ? "1" : "0"}
\taddonContent_Prop\t\t\t0 // TODO
}`)
    }

    FilesystemWrapper.rm(`${path}/${addon.publishedfileid}.${Game.getAddonExtension()}`)
    FilesystemWrapper.rm(`${path}/${addon.publishedfileid}.jpg`)
}

module.exports.install = async addon => {
    const path = `${Paths.getSteamApplications()}/common/${Game.getName()}/${Game.getSubdirectory()}/addons`

    {
        let installed = false
        let toInstall = []

        if (dependencies.specific[addon.publishedfileid] != null) {
            toInstall = dependencies.specific[addon.publishedfileid]

            toInstall.push(addon.publishedfileid)
        } else {
            for (const dependency of dependencies.generic) {
                if (!dependency.includes(addon.publishedfileid))
                    continue

                toInstall = dependency
                break
            }
        }

        for (const found of toInstall) {
            installed = true

            await internalInstall(path, module.exports.get(found, false)[0])
        }

        if (installed)
            return
    }

    await internalInstall(path, addon)
}

module.exports.download = async addon => {
    const subdirectory = `${process.cwd()}/${addon.title.replaceAll("/", "_")} ${addon.publishedfileid}`

    if (existsSync(subdirectory)) {
        Logger.error(`Already downloaded addon: [${addon.publishedfileid}] ${Strings.removeNewlineEnd(addon.title)}`)
        return
    }

    await internalInstall(Paths.getConfiguration(), addon)

    // TODO: Figure out how to just move instead
    FilesystemWrapper.cp(`${Paths.getConfiguration()}/${addon.publishedfileid}`, subdirectory, {
        recursive: true
    })
    FilesystemWrapper.rm(`${Paths.getConfiguration()}/${addon.publishedfileid}`, {
        recursive: true
    })
}
