// Purpose: Addon management
// Created on: 5/1/26 @ 2:29 AM

const {writeFileSync, rmSync, existsSync, mkdirSync} = require("fs")
const {execSync} = require("child_process")

const Strings = require("./strings")
const Paths = require("./paths")
const Logger = require("./logger")
const Collections = require("./collections")

let mods = null

module.exports.initialize = async () => {
    // FIXME: This sucks, but there isn't really much we can do about it... Too bad.
    mods = await (await fetch("http://10.0.44.20:5113/Mods/Left 4 Dead 2/data.json")).json()
}

module.exports.getAll = () => mods.response.publishedfiledetails

module.exports.find = (addonName, fuzzy) => {
    let addons = []

    addonName = addonName.toLowerCase()

    let checkTitle = title => title.toLowerCase().includes(addonName)
    let checkDescription = description => checkTitle(description)

    if (!fuzzy) {
        checkTitle = title => title.toLowerCase() === addonName
        checkDescription = description => false
    }

    for (const addon of mods.response.publishedfiledetails) {
        if (addon.result !== 1) {
            addon.title = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
            addon.description = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
            addon.tags = [{tag: "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"}]
        }

        if (!checkTitle(addon.title) && !checkDescription(addon.description)) {
            if (addon.publishedfileid === addonName) {
                addons.push(addon)
                continue
            }

            if (!fuzzy)
                continue

            let add = false

            for (const tag of addon.tags) {
                if (!tag.tag.toLowerCase().includes(addonName))
                    continue

                add = true
                break
            }

            if (!add)
                continue

            addons.push(addon)
            continue
        }

        addons.push(addon)
    }

    if (addons.length === 0) {
        Logger.log("Found no addons")
        process.exit(4)
    }

    return addons
}

const internalInstall = async (path, subdirectory, addon) => {
    Logger.log(`Downloading: [${addon.publishedfileid}] ${Strings.removeNewlineEnd(addon.title)}`)

    const vpk = await fetch(`http://10.0.44.20:5113/Mods/Left 4 Dead 2/${addon.publishedfileid}.vpk`)

    if (!vpk.ok) {
        Logger.log("Error while trying to download addon from server")
        process.exit(5)
    }

    writeFileSync(`${path}/${addon.publishedfileid}.vpk`, await vpk.bytes())

    const jpg = await fetch(`http://10.0.44.20:5113/Mods/Left 4 Dead 2/${addon.publishedfileid}.jpg`)

    if (!jpg.ok) {
        Logger.log("Error while trying to download image from server. Was this addon unavailable when added?")
        Logger.log("The addon should still work, but it might not have an image in the addons menu")
        return
    }

    writeFileSync(`${path}/${addon.publishedfileid}.jpg`, await jpg.bytes())

    let vpkedit = null

    try {
        vpkedit = execSync("command -v vpkeditcli").toString()
        vpkedit = vpkedit.substring(0, vpkedit.length - 1)
    } catch {
        Logger.log("VPKEdit is not installed. Unable to fix addon images")
        return
    }

    let magick = null

    try {
        magick = execSync("command -v magick").toString()
        magick = magick.substring(0, magick.length - 1)
    } catch {
        Logger.log("ImageMagick is not installed. Unable to fix addon images")
        return
    }

    try {
        execSync(`${vpkedit} "${path}/${addon.publishedfileid}.vpk" -o "${path}" --extract > /dev/null`)
    } catch {
        Logger.log("Failed to extract addon")
        return
    }

    if (!existsSync(`${path}/${subdirectory}`)) {
        Logger.log("Addon folder doesn't exist? Was the addon downloaded correctly?")
        return
    }

    try {
        execSync(`${magick} "${path}/${addon.publishedfileid}.jpg" -strip -sampling-factor 4:2:0 "${path}/${subdirectory}/addonimage.jpg"`)
    } catch {
        Logger.log("Failed to fix image")
    }

    if (!existsSync(`${path}/${subdirectory}/addoninfo.txt`)) {
        // TODO: Some flags are never set
        writeFileSync(`${path}/${subdirectory}/addoninfo.txt`,
            `"AddonInfo"
{
// Generated by SourceAddonsManager
\taddonversion\t\t"0.0"
\taddontitle\t\t\t"${Strings.removeNewlineEnd(addon.title.replaceAll("\"", "")).substring(0, 127)}"
\taddonauthor\t\t\t"${addon.creator.substring(0, 119)}"
\taddonDescription\t"${addon.description.substring(0, 1023).replaceAll("\"", "'")}"

\taddonContent_Campaign\t\t${addon.tags.filter(tag => tag.tag === "Campaigns").length !== 0 ? "1" : "0"}
\taddonContent_Map\t\t\t${addon.tags.filter(tag => tag.tag === "Campaigns").length !== 0 ? "1" : "0"}
\taddonContent_Skin\t\t\t${(addon.tags.filter(tag => tag.tag === "Textures").length !== 0 || addon.tags.filter(tag => tag.tag === "Models").length !== 0) ? "1" : "0"}
\taddonContent_weapon\t\t\t${addon.tags.filter(tag => tag.tag === "Weapons").length !== 0 ? "1" : "0"}
\taddonContent_BossInfected\t${(addon.tags.filter(tag => tag.tag === "Witch").length !== 0 || addon.tags.filter(tag => tag.tag === "Tank").length !== 0) ? "1" : "0"}
\taddonContent_CommonInfected\t${addon.tags.filter(tag => tag.tag === "Common Infected").length !== 0 ? "1" : "0"}
\taddonContent_Survivor\t\t${addon.tags.filter(tag => tag.tag === "Survivors").length !== 0 ? "1" : "0"}
\taddonContent_Sound\t\t\t${addon.tags.filter(tag => tag.tag === "Sounds").length !== 0 ? "1" : "0"}
\taddonContent_Music\t\t\t${addon.tags.filter(tag => tag.tag === "Sounds").length !== 0 ? "1" : "0"}
\taddonContent_Script\t\t\t${addon.tags.filter(tag => tag.tag === "Scripts").length !== 0 ? "1" : "0"}
\taddonContent_Prop\t\t\t0 // TODO
}`)
    }

    rmSync(`${path}/${addon.publishedfileid}.vpk`)
    rmSync(`${path}/${addon.publishedfileid}.jpg`)
}

module.exports.install = async addon => {
    await internalInstall(`${Paths.getSteamApplications()}/common/Left 4 Dead 2/left4dead2/addons`, addon.publishedfileid, addon)
}

module.exports.download = async addon => {
    const subdirectory = `${addon.title} ${addon.publishedfileid}`

    if (!existsSync(`${process.cwd()}/${subdirectory}`))
        mkdirSync(`${process.cwd()}/${subdirectory}`)

    await internalInstall(process.cwd(), subdirectory, addon)
}

module.exports.print = (addon, includeDescriptions) => {
    if (process.env.SAM_PARSABLE === "1") {
        Logger.debug(addon.publishedfileid)
        return
    }

    if (addon.result !== 1) {
        addon.title = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
        addon.description = "<[KRATCY]: THIS ADDON IS UNAVAILABLE ON THE STEAM WORKSHOP>"
    }

    let finalString = ""

    if (includeDescriptions)
        finalString += "\n============================================ "

    finalString += `[${addon.publishedfileid}] `

    if (includeDescriptions)
        finalString += "Addon: "

    finalString += Strings.removeNewlineEnd(addon.title)

    if (includeDescriptions)
        finalString += `\n${Strings.removeNewlineEnd(addon.description)}`

    Logger.log(finalString)
}

const internalInstallList = async (addonFunction, collectionFunction, ids) => {
    for (const id of ids) {
        {
            const collection = Collections.get(id)

            if (collection != null) {
                await (collectionFunction)(collection)
                continue
            }
        }

        const details = module.exports.find(id, false)

        if (details.length === 0 || details.length > 1) {
            Logger.log(`???????????????? ${id}, ${details.length}`)
            continue
        }

        await (addonFunction)(details[0])
    }
}

module.exports.installList = async ids => {
    await internalInstallList(module.exports.install, Collections.install, ids)
}

module.exports.downloadList = async ids => {
    await internalInstallList(module.exports.download, Collections.download, ids)
}
